name: money_plaza
description: An app build with the stacked framework

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  stacked: ^3.2.7
  stacked_services: ^1.0.0
  google_fonts: ^5.1.0
  flutter_switch: ^0.3.2
  localization: ^2.1.0
  easy_localization: ^3.0.2
  country_code_picker: ^3.0.0
  fluttertoast: ^8.2.2
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^5.7.2+3
  flutter_html_table: ^3.0.0-beta.2
  flutter_riverpod: ^2.3.7
  flutter_datetime_picker_plus: ^2.0.1
  image_picker: ^1.0.3
  url_launcher: ^6.1.13
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  flutter_launcher_icons: "^0.13.1"
  stacked_generator: ^1.0.0
  mockito: ^5.3.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/MoneyPlazaLogo.png"
  web:
    generate: true
    image_path: "assets/icons/MoneyPlazaLogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/MoneyPlazaLogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/MoneyPlazaLogo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/screens/
    - assets/icons/Landing_icons/
    - assets/icons/loans_icons/
    - assets/icons/credit_cards/
    - assets/icons/member_icons/
    - assets/icons/Morgages/
    - assets/icons/register_login_icons/
    - assets/screens/landing/
    - assets/images/
    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

