import 'package:money_plaza/ui/views/landing/startup/startup_view.dart';
import 'package:money_plaza/ui/views/loan/blnstransfer/blnstransfer_applyconfirm_view.dart';
import 'package:money_plaza/ui/views/loan/commerical_loan/comm_applyconfirm_view.dart';
import 'package:money_plaza/ui/views/loan/ownerloan/owner_applyconfirm_view.dart';
import 'package:money_plaza/ui/views/member/personal_info/personal_tabbar/tabbar4_widget/loan_record.dart';
import 'package:money_plaza/ui/views/survey_form/survey_form_view.dart';
import 'package:money_plaza/ui/widgets/web_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:money_plaza/ui/views/landing/landing_view.dart';
import 'package:money_plaza/ui/views/loan/loan_view.dart';
import 'package:money_plaza/ui/views/loan/calculator_result/calculator_result_view.dart';
import 'package:money_plaza/ui/views/loan/loancompare/loancompare_view.dart';
import 'package:money_plaza/ui/views/loan/apply_confirm/applyconfirm_view.dart';
import 'package:money_plaza/ui/views/loan/personal_loan/personalloan_view.dart';
import 'package:money_plaza/ui/views/loan/personal_loan/ploanreslut/ploanreslut_view.dart';
import 'package:money_plaza/ui/views/loan/ownerloan/ownerloan_view.dart';
import 'package:money_plaza/ui/views/loan/servayloanresult_view.dart';
import 'package:money_plaza/ui/views/landing/settings/settings_view.dart';
import 'package:money_plaza/ui/views/member_login/member_login_view.dart';
import 'package:money_plaza/ui/views/loan/blnstransfer/blnstransfer_view.dart';
import 'package:money_plaza/ui/views/loan/blnstransfer/transfer_result/transfer_result_view.dart';
import 'package:money_plaza/ui/views/loan/commerical_loan/commerical_loan_view.dart';
import 'package:money_plaza/ui/dialogs/filter/filter_dialog.dart';
import 'package:money_plaza/ui/dialogs/calculator/calculator_dialog.dart';
import 'package:money_plaza/ui/views/morgages/morgages_view.dart';
import 'package:money_plaza/ui/views/morgages/morgages_result/morgages_result_view.dart';
import 'package:money_plaza/ui/dialogs/reset_password/reset_password_dialog.dart';
import 'package:money_plaza/ui/dialogs/contact_us/contact_us_dialog.dart';
import 'package:money_plaza/ui/dialogs/morgages_filter/morgages_filter_dialog.dart';
import 'package:money_plaza/ui/views/survey_form/survey_splash_view.dart';
import 'package:money_plaza/ui/views/credit_card/credit_card_view.dart';
import 'package:money_plaza/ui/views/credit_card/credit_result/credit_result_view.dart';
import 'package:money_plaza/ui/dialogs/credit_card_filter/credit_card_filter_dialog.dart';
import 'package:money_plaza/ui/views/member/member_setting/member_setting_view.dart';
import 'package:money_plaza/ui/views/member/personal_info/personal_info_view.dart';
import 'package:money_plaza/ui/views/member/reward/reward_view.dart';
import 'package:money_plaza/ui/views/member/reward_application/reward_application_view.dart';
import 'package:money_plaza/ui/views/member/change_password/change_password_view.dart';
import 'package:money_plaza/ui/dialogs/detail_filte/detail_filte_dialog.dart';
import 'package:money_plaza/services/toaster_service.dart';
import '../ui/views/loan/personal_loan/applyconfirm_view.dart';
import 'package:money_plaza/services/api_helper_service.dart';
import 'package:money_plaza/ui/views/landing/settings/privacy_policy/privacy_policy_view.dart';
import 'package:money_plaza/ui/views/landing/settings/term_conditions/term_conditions_view.dart';
// @stacked-import

@StackedApp(
  routes: [
    MaterialRoute(page: StartupView),
    MaterialRoute(page: LandingView),
    MaterialRoute(page: LoanView),
    MaterialRoute(page: CalculatorResultView),
    MaterialRoute(page: LoancompareView),
    MaterialRoute(page: ApplyconfirmView),
    MaterialRoute(page: PersonalloanView),
    MaterialRoute(page: PloanreslutView),
    MaterialRoute(page: OwnerloanView),
    MaterialRoute(page: ServayLoanResultView),
    MaterialRoute(page: SettingsView),
    MaterialRoute(page: MemberLoginView),
    MaterialRoute(page: BlnstransferView),
    MaterialRoute(page: TransferResultView),
    MaterialRoute(page: CommericalLoanView),
    MaterialRoute(page: MorgagesView),
    MaterialRoute(page: MorgagesResultView),
    MaterialRoute(page: SurveySplashView),
    MaterialRoute(page: SurveyFormView),
    MaterialRoute(page: CreditCardView),
    MaterialRoute(page: CreditResultView),
    MaterialRoute(page: MemberSettingView),
    MaterialRoute(page: PersonalInfoView),
    MaterialRoute(page: RewardView),
    MaterialRoute(page: RewardApplicationView),
    MaterialRoute(page: ChangePasswordView),
    MaterialRoute(page: OwnerApplyConfirmView),
    MaterialRoute(page: PersonalloanApplyConfirmView),
    MaterialRoute(page: CommericalApplyConfirmView),
    MaterialRoute(page: BlnstransferloanApplyConfirmView),
    MaterialRoute(page: LoanRecordView),
    MaterialRoute(page: WebView),

    MaterialRoute(page: PrivacyPolicyView),
    MaterialRoute(page: TermConditionsView),
// @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: ToasterService),
    LazySingleton(classType: ApiHelperService),
// @stacked-service
  ],
  dialogs: [
    StackedDialog(classType: FilterDialog),
    StackedDialog(classType: CalculatorDialog),
    StackedDialog(classType: ResetPasswordDialog),
    StackedDialog(classType: ContactUsDialog),
    StackedDialog(classType: MorgagesFilterDialog),
    StackedDialog(classType: CreditCardFilterDialog),
    StackedDialog(classType: DetailFilteDialog),
// @stacked-dialog
  ],
)
class App {}
