class LoanCard {
  int id;
  int companyId;
  Company company;
  String type;
  bool invoiceFinancing;
  String displayColumn;
  int monthlyInterestRate;
  double apr;
  double interestRate;
  double minInterestRate;
  double maxInterestRate;
  int latePaymentFee;
  int minPayInterest;
  int minPayAbsolute;
  String advantage;
  String advantageCht;
  String feature;
  String summary;
  String summaryCht;
  String banner;
  String detailTitle;
  String detailTitleCht;
  String detail;
  String detailCht;
  String shareMsg;
  String shareMsgCht;
  int likeCount;
  String applyLink;
  String applyLinkCht;
  int ordering;
  bool showBanner;
  bool status;
  bool checkTu;
  String tuLevel;
  bool earlyRepaymentPenalty;
  String calculateMethod;
  String repaymentCalculateMethod;
  String applyButtonAction;
  int invoiceFinancingMinDays;
  int invoiceFinancingMaxDays;
  int minTenor;
  int maxTenor;
  int minAmount;
  int maxAmount;
  double maxDsr;
  int maxMue;
  int minIncome;
  bool pol;
  bool thirdParty;
  int prefer;
  String incentive;
  String incentiveCht;
  String previewToken;
  DateTime updateDate;
  DateTime createDate;
  int maxAvailableLoanAmount;
  int maxAvailableLoanAmountTenor;
  String scheduledPaymentAmount;
  String totalPaymentAmount;
  List<String> features;
  List<String> displayColumns;
  bool monthlyFlatRate;
  bool interestRateOnly;
  bool pureApr;
  String aprStr;
  bool customRate;

  LoanCard({
    required this.id,
    required this.companyId,
    required this.company,
    required this.type,
    required this.invoiceFinancing,
    required this.displayColumn,
    required this.monthlyInterestRate,
    required this.apr,
    required this.interestRate,
    required this.minInterestRate,
    required this.maxInterestRate,
    required this.latePaymentFee,
    required this.minPayInterest,
    required this.minPayAbsolute,
    required this.advantage,
    required this.advantageCht,
    required this.feature,
    required this.summary,
    required this.summaryCht,
    required this.banner,
    required this.detailTitle,
    required this.detailTitleCht,
    required this.detail,
    required this.detailCht,
    required this.shareMsg,
    required this.shareMsgCht,
    required this.likeCount,
    required this.applyLink,
    required this.applyLinkCht,
    required this.ordering,
    required this.showBanner,
    required this.status,
    required this.checkTu,
    required this.tuLevel,
    required this.earlyRepaymentPenalty,
    required this.calculateMethod,
    required this.repaymentCalculateMethod,
    required this.applyButtonAction,
    required this.invoiceFinancingMinDays,
    required this.invoiceFinancingMaxDays,
    required this.minTenor,
    required this.maxTenor,
    required this.minAmount,
    required this.maxAmount,
    required this.maxDsr,
    required this.maxMue,
    required this.minIncome,
    required this.pol,
    required this.thirdParty,
    required this.prefer,
    required this.incentive,
    required this.incentiveCht,
    required this.previewToken,
    required this.updateDate,
    required this.createDate,
    required this.maxAvailableLoanAmount,
    required this.maxAvailableLoanAmountTenor,
    required this.scheduledPaymentAmount,
    required this.totalPaymentAmount,
    required this.features,
    required this.displayColumns,
    required this.monthlyFlatRate,
    required this.interestRateOnly,
    required this.pureApr,
    required this.aprStr,
    required this.customRate,
  });
}

class Company {
  int id;
  String logo;
  String name;
  String nameCht;
  String licenseNo;
  bool bank;
  int ordering;
  int loanOrdering;
  int cardOrdering;
  int mortgageOrdering;
  int accountOrdering;
  int insuranceOrdering;
  DateTime updateDate;
  DateTime createDate;
  String signLogoUrl;

  Company({
    required this.id,
    required this.logo,
    required this.name,
    required this.nameCht,
    required this.licenseNo,
    required this.bank,
    required this.ordering,
    required this.loanOrdering,
    required this.cardOrdering,
    required this.mortgageOrdering,
    required this.accountOrdering,
    required this.insuranceOrdering,
    required this.updateDate,
    required this.createDate,
    required this.signLogoUrl,
  });
}
